# Recreate and initialize the local development database on startup.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/sqlite/schema.sql
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
logging.level.org.springframework.security=DEBUG
spring.web.error.include-message=always
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=always
