spring.application.name=app
server.port=3500

spring.datasource.url=jdbc:sqlite:superchef.db?journal_mode=WAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA busy_timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.error.include-message=always
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always