spring.datasource.url=jdbc:sqlite:superchef.db?journal_mode=WAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/sqlite/schema.sql
# Run Hibernate initialization before schema.sql
spring.jpa.defer-datasource-initialization=true